[package]
name = "shadowsocks-rust"
version = "1.9.0"
authors = ["Shadowsocks Contributors"]
description = "shadowsocks is a fast tunnel proxy that helps you bypass firewalls."
repository = "https://github.com/shadowsocks/shadowsocks-rust"
readme = "README.md"
documentation = "https://docs.rs/shadowsocks-rust"
keywords = ["shadowsocks", "proxy", "socks", "socks5", "firewall"]
license = "MIT"
edition = "2018"

[badges]
maintenance = { status = "passively-maintained" }

[lib]
name = "shadowsocks"

[[bin]]
name = "sslocal"
path = "src/bin/local.rs"

[[bin]]
name = "ssserver"
path = "src/bin/server.rs"

[[bin]]
name = "ssurl"
path = "src/bin/ssurl.rs"

[[bin]]
name = "ssmanager"
path = "src/bin/manager.rs"

[profile.release]
lto = "fat"
codegen-units = 1
incremental = false
panic = "abort"

[features]
default = [
    "trust-dns",
    "local-http",
    "local-http-rustls",
    "local-tunnel",
    "local-socks4"
]
# Uses single-threaded scheduler instead of default multi-threaded
single-threaded = []
# Enables trust-dns for replacing tokio's builtin DNS resolver
trust-dns = ["trust-dns-resolver"]
dns-over-tls = ["trust-dns", "trust-dns-resolver/dns-over-rustls"]
dns-over-https = ["trust-dns", "trust-dns-resolver/dns-over-https-rustls"]
# Enable DNS-relay
local-dns = ["trust-dns-proto"]
# Backward compatibility, DO NOT USE
local-dns-relay = ["local-dns"]
# Enable client flow statistic report
# Currently is only used in Android
local-flow-stat = []
# Enable HTTP protocol for sslocal
local-http = ["hyper", "http", "tower"]
local-http-native-tls = ["tokio-native-tls", "native-tls"]
local-http-rustls = ["tokio-rustls", "webpki-roots", "rustls-native-certs"]
# Enable REDIR protocol for sslocal
# (transparent proxy)
local-redir = []
# Enable tunnel protocol for sslocal
local-tunnel = []
# Enable SOCKS4/4a protocol for sslocal
local-socks4 = []
# Enable jemalloc for binaries
jemalloc = ["jemallocator"]
# Enable bundled tcmalloc
tcmalloc-vendored = ["tcmalloc/bundled"]


[target.'cfg(any(target_arch = "x86", target_arch = "x86_64"))'.dependencies]
shadowsocks-crypto = { version = "0.1", features = [ "ring" ] }

[target.'cfg(any(target_arch = "arm", target_arch = "aarch64"))'.dependencies]
shadowsocks-crypto = { version = "0.1", features = [ "ring" ] }

[target.'cfg(not(any(target_arch = "x86", target_arch = "x86_64", target_arch = "arm", target_arch = "aarch64")))'.dependencies]
shadowsocks-crypto = { version = "0.1", features = [ ] }

[dependencies]
log    = "0.4"
rand   = "0.7"
clap   = { version = "2.33", features = ["wrap_help", "suggestions"] }
log4rs = "0.13"
libc   = "0.2"
bytes  = "0.5"
url    = "2.1"
regex  = "1"
cfg-if = "1.0"
base64 = "0.13"
byteorder   = "1"
byte_string = "1.0"
lazy_static = "1.4"

ring      = "0.16"

spin    = "0.7"
mio     = "0.6"
mio-uds = "0.6"
socket2 = "0.3"
pin-project = "1.0"
bloomfilter = "^1.0.2"

json5 = "0.2"
futures = "0.3"
async-trait = "0.1"

tokio = { version = "^0.3", features = [ "full" ] }
tokio-native-tls = { version = "0.2", optional = true }
native-tls = { version = "0.2", optional = true }
tokio-rustls = { version = "0.20", optional = true }
webpki-roots = { version = "0.20", optional = true }
rustls-native-certs = { version = "0.4", optional = true }

qrcode = { version = "0.12", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_urlencoded = "0.7"

lru_time_cache = "0.11"
http  = { version = "0.2",  optional = true }
# trust-dns-resolver = { version = "0.19", optional = true }
# trust-dns-proto = "0.19"
trust-dns-resolver = { git = "https://github.com/bluejekyll/trust-dns.git", optional = true, branch = "upgrade-to-tokio-0.3", features = ["serde-config"] }
trust-dns-proto = { git = "https://github.com/bluejekyll/trust-dns.git", optional = true, branch = "upgrade-to-tokio-0.3" }
hyper = { git = "https://github.com/hyperium/hyper.git", optional = true }
tower = { git = "https://github.com/tower-rs/tower.git", optional = true }

strum = "0.19"
strum_macros = "0.19"
ipnet = "2.2"
iprange = "0.6"

mimalloc     = { version = "0.1", optional = true }
tcmalloc     = { version = "0.3", optional = true }
jemallocator = { version = "0.3", optional = true }


[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["mswsock", "winsock2"] }

# Just for the ioctl call macro
[target.'cfg(any(target_os = "macos", target_os = "ios", target_os = "freebsd", target_os = "netbsd", target_os = "openbsd"))'.dependencies]
nix = "0.19"

[target.'cfg(unix)'.dependencies]
daemonize = "^0.4.1"

[dev-dependencies]
env_logger = "0.8"

[patch.crates-io]
h2 = { git = "https://github.com/hyperium/h2.git" }